import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import galaxy from '../images/galaxy.jpg'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'
import Link from 'next/link'

const Home: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Parallax pages={3}>

      <ParallaxLayer
        offset={0}
        speed={0.1}
        factor={3}>
        <Image layout="fill" objectFit="cover" src={galaxy} quality={100} alt="Space background" />
      </ParallaxLayer>
      <ParallaxLayer
        offset={0}
        speed={1}
        className={styles.main}>
        <h1 className={styles.title}>
          Hello 👋, I&apos;m CodeDoctor
        </h1>
        <p className={styles.description}>
          I&apos;m a german front- and backend developer
        </p>
      </ParallaxLayer>

      <ParallaxLayer
        offset={1}
        speed={1}
        sticky={{ start: 1, end: 3 }}
      >
        <h2 className={styles.subtitle}>
          Skills
        </h2>
      </ParallaxLayer>
      <ParallaxLayer
        offset={1.25}
        speed={1}
        style={{ display: 'flex', alignItems: 'center' }}
      ><>
          <h3 className={styles.sectionTitle}>
            Programming Languages
          </h3>
          <ul className={styles.cardList}>
            <li>C#</li>
            <li>Dart</li>
            <li>TypeScript</li>
            <li>Java</li>
            <li>Ruby</li>
            <li>Python</li>
            <li>JavaScript</li>
            <li>GodotScript</li>
          </ul>
          <h3 className={styles.sectionTitle}>
            Frameworks
          </h3>
          <ul className={styles.cardList}>
            <li>React</li>
            <li>Next.js</li>
            <li>Flutter</li>
            <li>Unity</li>
            <li>Godot Engine</li>
          </ul>
          <h3 className={styles.sectionTitle}>
            Tools
          </h3>
          <ul className={styles.cardList}>
            <li><Link href="https://git-scm.com">Git</Link></li>
            <li><Link href="https://github.com">GitHub (Repositories, Actions, Issues, Projects)</Link></li>
            <li><Link href="https://gitlab.com">GitLab</Link></li>
            <li><Link href="https://gitea.io">Gitea</Link></li>
            <li><Link href="https://code.visualstudio.com">Visual Studio Code</Link></li>
            <li><Link href="https://www.jetbrains.com/idea/">IntelliJ</Link></li>
            <li><Link href="https://discord.com">Discord</Link></li>
            <li><Link href="https://slack.com">Slack</Link></li>
            <li><Link href="https://trello.com">Trello</Link></li>
            <li><Link href="https://www.atlassian.com/software/confluence">Confluence</Link></li>
          </ul>
        </>
      </ParallaxLayer>
    </Parallax>
  </div>
)

export default Home
